
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'INSTRUMENT NOTE PARAMETERfile : file item\n            | itemitem : NOTE\n            | INSTRUMENT\n            | PARAMETER'
    
_lr_action_items = {'NOTE':([0,1,2,3,4,5,6,],[3,3,-2,-3,-4,-5,-1,]),'INSTRUMENT':([0,1,2,3,4,5,6,],[4,4,-2,-3,-4,-5,-1,]),'PARAMETER':([0,1,2,3,4,5,6,],[5,5,-2,-3,-4,-5,-1,]),'$end':([1,2,3,4,5,6,],[0,-2,-3,-4,-5,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'file':([0,],[1,]),'item':([0,1,],[2,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> file","S'",1,None,None,None),
  ('file -> file item','file',2,'p_file','sf22yue.py',27),
  ('file -> item','file',1,'p_file','sf22yue.py',28),
  ('item -> NOTE','item',1,'p_item','sf22yue.py',32),
  ('item -> INSTRUMENT','item',1,'p_item','sf22yue.py',33),
  ('item -> PARAMETER','item',1,'p_item','sf22yue.py',34),
]
