
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DURATION INSTRUMENT NOTE TEMPO VELOCITYstatements : statement\n                      | statements statementstatement : note_statement\n                     | instrument_statement\n                     | tempo_statement\n                     | duration_statement\n                     | velocity_statementnote_statement : NOTE DURATION VELOCITYinstrument_statement : INSTRUMENTtempo_statement : TEMPOduration_statement : DURATIONvelocity_statement : VELOCITY'
    
_lr_action_items = {'NOTE':([0,1,2,3,4,5,6,7,9,10,11,12,13,15,],[8,8,-1,-3,-4,-5,-6,-7,-11,-12,-9,-10,-2,-8,]),'INSTRUMENT':([0,1,2,3,4,5,6,7,9,10,11,12,13,15,],[11,11,-1,-3,-4,-5,-6,-7,-11,-12,-9,-10,-2,-8,]),'TEMPO':([0,1,2,3,4,5,6,7,9,10,11,12,13,15,],[12,12,-1,-3,-4,-5,-6,-7,-11,-12,-9,-10,-2,-8,]),'DURATION':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,15,],[9,9,-1,-3,-4,-5,-6,-7,14,-11,-12,-9,-10,-2,-8,]),'VELOCITY':([0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,],[10,10,-1,-3,-4,-5,-6,-7,-11,-12,-9,-10,-2,15,-8,]),'$end':([1,2,3,4,5,6,7,9,10,11,12,13,15,],[0,-1,-3,-4,-5,-6,-7,-11,-12,-9,-10,-2,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,],[1,]),'statement':([0,1,],[2,13,]),'note_statement':([0,1,],[3,3,]),'instrument_statement':([0,1,],[4,4,]),'tempo_statement':([0,1,],[5,5,]),'duration_statement':([0,1,],[6,6,]),'velocity_statement':([0,1,],[7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> statement','statements',1,'p_statements','yinplayer.py',51),
  ('statements -> statements statement','statements',2,'p_statements','yinplayer.py',52),
  ('statement -> note_statement','statement',1,'p_statement','yinplayer.py',59),
  ('statement -> instrument_statement','statement',1,'p_statement','yinplayer.py',60),
  ('statement -> tempo_statement','statement',1,'p_statement','yinplayer.py',61),
  ('statement -> duration_statement','statement',1,'p_statement','yinplayer.py',62),
  ('statement -> velocity_statement','statement',1,'p_statement','yinplayer.py',63),
  ('note_statement -> NOTE DURATION VELOCITY','note_statement',3,'p_note_statement','yinplayer.py',67),
  ('instrument_statement -> INSTRUMENT','instrument_statement',1,'p_instrument_statement','yinplayer.py',71),
  ('tempo_statement -> TEMPO','tempo_statement',1,'p_tempo_statement','yinplayer.py',75),
  ('duration_statement -> DURATION','duration_statement',1,'p_duration_statement','yinplayer.py',79),
  ('velocity_statement -> VELOCITY','velocity_statement',1,'p_velocity_statement','yinplayer.py',83),
]
